/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interdisciplinar;

import comum.Banco;
import comum.Util;
import comum.ValidacaoDeFormularios;
import entidades.Loja;

/**
 *
 * @author Lizandra
 */
public class TelaCadastroLoja extends javax.swing.JFrame {

    private Loja _loja;
    private Banco _banco;

    public TelaCadastroLoja(int id) {

        this();
        carregarLojaId(id);
    }

    /**
     * Creates new form TelaCadastroLoja
     */
    public TelaCadastroLoja() {
        initComponents();

        this.setLocationRelativeTo(null);
        this.setResizable(false);

        _banco = new Banco();
    }

    private void carregarLojaId(int id) {

        _loja = _banco.buscarLojaPorId(id);
        txtNomeLoja.setText(_loja.getNome());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNomeLoja = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de lojas");
        setResizable(false);

        jLabel1.setText("Nome da loja");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:

        if (!formularioValido()) {
            return;
        }

        // Se o loja estiver null significa que o usuario
        // esta criando uma nova loja
        if (_loja == null) {
            salvarNovaLoja();
            return;
        }

        // se a varival local _loja tem conteudo, significa que o
        // usuario quer alterar a loja selecionado.
        atualizarLoja();

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void atualizarLoja() {
        
        _loja.setNome(txtNomeLoja.getText());
        boolean atualizou = _banco.atualizarLoja(_loja);

        if (atualizou) {
            Util.mensagemDeAlerta("Estado atualizado com sucesso", this);
        } else {
            Util.mensagemDeAlerta("Ocorreu um erro ao tentar atualizar a loja no banco de dados", this);
        }

        this.dispose();

    }

    private void salvarNovaLoja() {

        String nome = txtNomeLoja.getText();

        boolean salvou = new Banco().novaLoja(nome);
        if (salvou) {
            Util.mensagemDeAlerta("Nova loja cadastrada com sucesso", this);
        } else {
            Util.mensagemDeAlerta("Ocorreu um erro ao tentar salvar", this);
        }

        txtNomeLoja.setText("");

    }

    private boolean formularioValido() {

        if (!ValidacaoDeFormularios.campoTextoEstaValido("uf", txtNomeLoja, 2, this)) {
            return false;
        }

        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroLoja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNomeLoja;
    // End of variables declaration//GEN-END:variables
}
